### ISSUE TITLE
questions on overfitting issue and co-existing emotions percentage calculation

### ISSUE THREAD

**Issue by BalasubramanyamEvani** [hasanhuz/SpanEmo#13]
Hello,

Thank you for sharing your work on multi-label emotion recognition. I successfully ran the code and got some results, and I made sure to use the same parameters as described in the paper (made sure loss-type is joint loss). But, the model after four epochs seems to be overfitting a lot. 

I was just wondering if you observed this phenomenon and what could be the cause if you didn't, I request you to kindly let me know if I'm doing something wrong.

Apart from the above question, I also had a doubt about what co-existing percentage refers to in the paper and how it was calculated.

I'd greatly appreciate some clarifications.

Thank you!

**Comment by hasanhuz** [comment]
Hi there, thank you for your interest in our work. For the first question, I don't remember the exact details but I expect to see some overfitting if the model reaches several epochs, which could be caused by the size of the data. Try to reduce the number of batch size, this may help a little bit.

For the second question, it refers to the number of emotions co-exist in the data. For example, joy and love seems to co-exist in many examples than other types of emotion. In short, the percentage demonstrated this co-existing behaviour across the data.

Hope this helps,
Hassan
